const Notes: Record<string, string> = {
    C3: "/sounds/piano/C3.mp3",
    Db3: "/sounds/piano/Db3.mp3",
    D3: "/sounds/piano/D3.mp3",
    Eb3: "/sounds/piano/Eb3.mp3",
    E3: "/sounds/piano/E3.mp3",
    F3: "/sounds/piano/F3.mp3",
    Gb3: "/sounds/piano/Gb3.mp3",
    G3: "/sounds/piano/G3.mp3",
    Ab3: "/sounds/piano/Ab3.mp3",
    A3: "/sounds/piano/A3.mp3",
    Bb3: "/sounds/piano/Bb3.mp3",
    B3: "/sounds/piano/B3.mp3",
    C4: "/sounds/piano/C4.mp3",
    Db4: "/sounds/piano/Db4.mp3",
    D4: "/sounds/piano/D4.mp3",
    Eb4: "/sounds/piano/Eb4.mp3",
    E4: "/sounds/piano/E4.mp3",
    F4: "/sounds/piano/F4.mp3",
    Gb4: "/sounds/piano/Gb4.mp3",
    G4: "/sounds/piano/G4.mp3",
    Ab4: "/sounds/piano/Ab4.mp3",
    A4: "/sounds/piano/A4.mp3",
    Bb4: "/sounds/piano/Bb4.mp3",
    B4: "/sounds/piano/B4.mp3",
    C5: "/sounds/piano/C5.mp3",
    Db5: "/sounds/piano/Db5.mp3",
    D5: "/sounds/piano/D5.mp3",
    Eb5: "/sounds/piano/Eb5.mp3",
    E5: "/sounds/piano/E5.mp3",
    F5: "/sounds/piano/F5.mp3",
    Gb5: "/sounds/piano/Gb5.mp3",
    G5: "/sounds/piano/G5.mp3",
    Ab5: "/sounds/piano/Ab5.mp3",
    A5: "/sounds/piano/A5.mp3",
    Bb5: "/sounds/piano/Bb5.mp3",
    B5: "/sounds/piano/B5.mp3",
};

export default Notes;
